/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeachersRouteImport } from './routes/teachers'
import { Route as SupportStaffRouteImport } from './routes/support-staff'
import { Route as StudentsBodyRouteImport } from './routes/students-body'
import { Route as StatutoryBodyRouteImport } from './routes/statutory-body'
import { Route as SsrRouteImport } from './routes/ssr'
import { Route as SolarPlantRouteImport } from './routes/solar-plant'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ScoutsGuidesRouteImport } from './routes/scouts-guides'
import { Route as ScholarshipsRouteImport } from './routes/scholarships'
import { Route as RoutineRouteImport } from './routes/routine'
import { Route as ProspectusRouteImport } from './routes/prospectus'
import { Route as PrincipalRouteImport } from './routes/principal'
import { Route as PerspectivePlanRouteImport } from './routes/perspective-plan'
import { Route as NssRouteImport } from './routes/nss'
import { Route as NoticesRouteImport } from './routes/notices'
import { Route as NirfRouteImport } from './routes/nirf'
import { Route as NccRouteImport } from './routes/ncc'
import { Route as MuseumRouteImport } from './routes/museum'
import { Route as MottoRouteImport } from './routes/motto'
import { Route as MissionVisionRouteImport } from './routes/mission-vision'
import { Route as MentorMenteeRouteImport } from './routes/mentor-mentee'
import { Route as LibraryRouteImport } from './routes/library'
import { Route as LegacyRouteImport } from './routes/legacy'
import { Route as LeadersRouteImport } from './routes/leaders'
import { Route as IqacMinutesRouteImport } from './routes/iqac-minutes'
import { Route as IqacRouteImport } from './routes/iqac'
import { Route as IdpRouteImport } from './routes/idp'
import { Route as IctClassroomsRouteImport } from './routes/ict-classrooms'
import { Route as GalleryRouteImport } from './routes/gallery'
import { Route as FeesWaiverRouteImport } from './routes/fees-waiver'
import { Route as FacultiesRouteImport } from './routes/faculties'
import { Route as FacilitiesPwdRouteImport } from './routes/facilities-pwd'
import { Route as EnvironmentAuditRouteImport } from './routes/environment-audit'
import { Route as EmblemRouteImport } from './routes/emblem'
import { Route as DepartmentsRouteImport } from './routes/departments'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ComputerLabRouteImport } from './routes/computer-lab'
import { Route as CollegeMagazineRouteImport } from './routes/college-magazine'
import { Route as CodeOfConductRouteImport } from './routes/code-of-conduct'
import { Route as CellsClubsRouteImport } from './routes/cells-clubs'
import { Route as CareerGuidanceRouteImport } from './routes/career-guidance'
import { Route as BestPracticesRouteImport } from './routes/best-practices'
import { Route as AqarRouteImport } from './routes/aqar'
import { Route as AnthemRouteImport } from './routes/anthem'
import { Route as AnnualReportRouteImport } from './routes/annual-report'
import { Route as AlumniRegistrationRouteImport } from './routes/alumni-registration'
import { Route as AlumniOfficeBearersRouteImport } from './routes/alumni-office-bearers'
import { Route as AlumniAchievementsRouteImport } from './routes/alumni-achievements'
import { Route as AisheRouteImport } from './routes/aishe'
import { Route as AdmissionRouteImport } from './routes/admission'
import { Route as AchievementsRouteImport } from './routes/achievements'
import { Route as AcademicCalendarRouteImport } from './routes/academic-calendar'
import { Route as AcademicAuditRouteImport } from './routes/academic-audit'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TeachersRoute = TeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => rootRouteImport,
} as any)
const SupportStaffRoute = SupportStaffRouteImport.update({
  id: '/support-staff',
  path: '/support-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentsBodyRoute = StudentsBodyRouteImport.update({
  id: '/students-body',
  path: '/students-body',
  getParentRoute: () => rootRouteImport,
} as any)
const StatutoryBodyRoute = StatutoryBodyRouteImport.update({
  id: '/statutory-body',
  path: '/statutory-body',
  getParentRoute: () => rootRouteImport,
} as any)
const SsrRoute = SsrRouteImport.update({
  id: '/ssr',
  path: '/ssr',
  getParentRoute: () => rootRouteImport,
} as any)
const SolarPlantRoute = SolarPlantRouteImport.update({
  id: '/solar-plant',
  path: '/solar-plant',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ScoutsGuidesRoute = ScoutsGuidesRouteImport.update({
  id: '/scouts-guides',
  path: '/scouts-guides',
  getParentRoute: () => rootRouteImport,
} as any)
const ScholarshipsRoute = ScholarshipsRouteImport.update({
  id: '/scholarships',
  path: '/scholarships',
  getParentRoute: () => rootRouteImport,
} as any)
const RoutineRoute = RoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => rootRouteImport,
} as any)
const ProspectusRoute = ProspectusRouteImport.update({
  id: '/prospectus',
  path: '/prospectus',
  getParentRoute: () => rootRouteImport,
} as any)
const PrincipalRoute = PrincipalRouteImport.update({
  id: '/principal',
  path: '/principal',
  getParentRoute: () => rootRouteImport,
} as any)
const PerspectivePlanRoute = PerspectivePlanRouteImport.update({
  id: '/perspective-plan',
  path: '/perspective-plan',
  getParentRoute: () => rootRouteImport,
} as any)
const NssRoute = NssRouteImport.update({
  id: '/nss',
  path: '/nss',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticesRoute = NoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => rootRouteImport,
} as any)
const NirfRoute = NirfRouteImport.update({
  id: '/nirf',
  path: '/nirf',
  getParentRoute: () => rootRouteImport,
} as any)
const NccRoute = NccRouteImport.update({
  id: '/ncc',
  path: '/ncc',
  getParentRoute: () => rootRouteImport,
} as any)
const MuseumRoute = MuseumRouteImport.update({
  id: '/museum',
  path: '/museum',
  getParentRoute: () => rootRouteImport,
} as any)
const MottoRoute = MottoRouteImport.update({
  id: '/motto',
  path: '/motto',
  getParentRoute: () => rootRouteImport,
} as any)
const MissionVisionRoute = MissionVisionRouteImport.update({
  id: '/mission-vision',
  path: '/mission-vision',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorMenteeRoute = MentorMenteeRouteImport.update({
  id: '/mentor-mentee',
  path: '/mentor-mentee',
  getParentRoute: () => rootRouteImport,
} as any)
const LibraryRoute = LibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => rootRouteImport,
} as any)
const LegacyRoute = LegacyRouteImport.update({
  id: '/legacy',
  path: '/legacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LeadersRoute = LeadersRouteImport.update({
  id: '/leaders',
  path: '/leaders',
  getParentRoute: () => rootRouteImport,
} as any)
const IqacMinutesRoute = IqacMinutesRouteImport.update({
  id: '/iqac-minutes',
  path: '/iqac-minutes',
  getParentRoute: () => rootRouteImport,
} as any)
const IqacRoute = IqacRouteImport.update({
  id: '/iqac',
  path: '/iqac',
  getParentRoute: () => rootRouteImport,
} as any)
const IdpRoute = IdpRouteImport.update({
  id: '/idp',
  path: '/idp',
  getParentRoute: () => rootRouteImport,
} as any)
const IctClassroomsRoute = IctClassroomsRouteImport.update({
  id: '/ict-classrooms',
  path: '/ict-classrooms',
  getParentRoute: () => rootRouteImport,
} as any)
const GalleryRoute = GalleryRouteImport.update({
  id: '/gallery',
  path: '/gallery',
  getParentRoute: () => rootRouteImport,
} as any)
const FeesWaiverRoute = FeesWaiverRouteImport.update({
  id: '/fees-waiver',
  path: '/fees-waiver',
  getParentRoute: () => rootRouteImport,
} as any)
const FacultiesRoute = FacultiesRouteImport.update({
  id: '/faculties',
  path: '/faculties',
  getParentRoute: () => rootRouteImport,
} as any)
const FacilitiesPwdRoute = FacilitiesPwdRouteImport.update({
  id: '/facilities-pwd',
  path: '/facilities-pwd',
  getParentRoute: () => rootRouteImport,
} as any)
const EnvironmentAuditRoute = EnvironmentAuditRouteImport.update({
  id: '/environment-audit',
  path: '/environment-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const EmblemRoute = EmblemRouteImport.update({
  id: '/emblem',
  path: '/emblem',
  getParentRoute: () => rootRouteImport,
} as any)
const DepartmentsRoute = DepartmentsRouteImport.update({
  id: '/departments',
  path: '/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ComputerLabRoute = ComputerLabRouteImport.update({
  id: '/computer-lab',
  path: '/computer-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeMagazineRoute = CollegeMagazineRouteImport.update({
  id: '/college-magazine',
  path: '/college-magazine',
  getParentRoute: () => rootRouteImport,
} as any)
const CodeOfConductRoute = CodeOfConductRouteImport.update({
  id: '/code-of-conduct',
  path: '/code-of-conduct',
  getParentRoute: () => rootRouteImport,
} as any)
const CellsClubsRoute = CellsClubsRouteImport.update({
  id: '/cells-clubs',
  path: '/cells-clubs',
  getParentRoute: () => rootRouteImport,
} as any)
const CareerGuidanceRoute = CareerGuidanceRouteImport.update({
  id: '/career-guidance',
  path: '/career-guidance',
  getParentRoute: () => rootRouteImport,
} as any)
const BestPracticesRoute = BestPracticesRouteImport.update({
  id: '/best-practices',
  path: '/best-practices',
  getParentRoute: () => rootRouteImport,
} as any)
const AqarRoute = AqarRouteImport.update({
  id: '/aqar',
  path: '/aqar',
  getParentRoute: () => rootRouteImport,
} as any)
const AnthemRoute = AnthemRouteImport.update({
  id: '/anthem',
  path: '/anthem',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnualReportRoute = AnnualReportRouteImport.update({
  id: '/annual-report',
  path: '/annual-report',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniRegistrationRoute = AlumniRegistrationRouteImport.update({
  id: '/alumni-registration',
  path: '/alumni-registration',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniOfficeBearersRoute = AlumniOfficeBearersRouteImport.update({
  id: '/alumni-office-bearers',
  path: '/alumni-office-bearers',
  getParentRoute: () => rootRouteImport,
} as any)
const AlumniAchievementsRoute = AlumniAchievementsRouteImport.update({
  id: '/alumni-achievements',
  path: '/alumni-achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AisheRoute = AisheRouteImport.update({
  id: '/aishe',
  path: '/aishe',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmissionRoute = AdmissionRouteImport.update({
  id: '/admission',
  path: '/admission',
  getParentRoute: () => rootRouteImport,
} as any)
const AchievementsRoute = AchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicCalendarRoute = AcademicCalendarRouteImport.update({
  id: '/academic-calendar',
  path: '/academic-calendar',
  getParentRoute: () => rootRouteImport,
} as any)
const AcademicAuditRoute = AcademicAuditRouteImport.update({
  id: '/academic-audit',
  path: '/academic-audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-audit': typeof AcademicAuditRoute
  '/academic-calendar': typeof AcademicCalendarRoute
  '/achievements': typeof AchievementsRoute
  '/admission': typeof AdmissionRoute
  '/aishe': typeof AisheRoute
  '/alumni-achievements': typeof AlumniAchievementsRoute
  '/alumni-office-bearers': typeof AlumniOfficeBearersRoute
  '/alumni-registration': typeof AlumniRegistrationRoute
  '/annual-report': typeof AnnualReportRoute
  '/anthem': typeof AnthemRoute
  '/aqar': typeof AqarRoute
  '/best-practices': typeof BestPracticesRoute
  '/career-guidance': typeof CareerGuidanceRoute
  '/cells-clubs': typeof CellsClubsRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/college-magazine': typeof CollegeMagazineRoute
  '/computer-lab': typeof ComputerLabRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/departments': typeof DepartmentsRoute
  '/emblem': typeof EmblemRoute
  '/environment-audit': typeof EnvironmentAuditRoute
  '/facilities-pwd': typeof FacilitiesPwdRoute
  '/faculties': typeof FacultiesRoute
  '/fees-waiver': typeof FeesWaiverRoute
  '/gallery': typeof GalleryRoute
  '/ict-classrooms': typeof IctClassroomsRoute
  '/idp': typeof IdpRoute
  '/iqac': typeof IqacRoute
  '/iqac-minutes': typeof IqacMinutesRoute
  '/leaders': typeof LeadersRoute
  '/legacy': typeof LegacyRoute
  '/library': typeof LibraryRoute
  '/mentor-mentee': typeof MentorMenteeRoute
  '/mission-vision': typeof MissionVisionRoute
  '/motto': typeof MottoRoute
  '/museum': typeof MuseumRoute
  '/ncc': typeof NccRoute
  '/nirf': typeof NirfRoute
  '/notices': typeof NoticesRoute
  '/nss': typeof NssRoute
  '/perspective-plan': typeof PerspectivePlanRoute
  '/principal': typeof PrincipalRoute
  '/prospectus': typeof ProspectusRoute
  '/routine': typeof RoutineRoute
  '/scholarships': typeof ScholarshipsRoute
  '/scouts-guides': typeof ScoutsGuidesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar-plant': typeof SolarPlantRoute
  '/ssr': typeof SsrRoute
  '/statutory-body': typeof StatutoryBodyRoute
  '/students-body': typeof StudentsBodyRoute
  '/support-staff': typeof SupportStaffRoute
  '/teachers': typeof TeachersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-audit': typeof AcademicAuditRoute
  '/academic-calendar': typeof AcademicCalendarRoute
  '/achievements': typeof AchievementsRoute
  '/admission': typeof AdmissionRoute
  '/aishe': typeof AisheRoute
  '/alumni-achievements': typeof AlumniAchievementsRoute
  '/alumni-office-bearers': typeof AlumniOfficeBearersRoute
  '/alumni-registration': typeof AlumniRegistrationRoute
  '/annual-report': typeof AnnualReportRoute
  '/anthem': typeof AnthemRoute
  '/aqar': typeof AqarRoute
  '/best-practices': typeof BestPracticesRoute
  '/career-guidance': typeof CareerGuidanceRoute
  '/cells-clubs': typeof CellsClubsRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/college-magazine': typeof CollegeMagazineRoute
  '/computer-lab': typeof ComputerLabRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/departments': typeof DepartmentsRoute
  '/emblem': typeof EmblemRoute
  '/environment-audit': typeof EnvironmentAuditRoute
  '/facilities-pwd': typeof FacilitiesPwdRoute
  '/faculties': typeof FacultiesRoute
  '/fees-waiver': typeof FeesWaiverRoute
  '/gallery': typeof GalleryRoute
  '/ict-classrooms': typeof IctClassroomsRoute
  '/idp': typeof IdpRoute
  '/iqac': typeof IqacRoute
  '/iqac-minutes': typeof IqacMinutesRoute
  '/leaders': typeof LeadersRoute
  '/legacy': typeof LegacyRoute
  '/library': typeof LibraryRoute
  '/mentor-mentee': typeof MentorMenteeRoute
  '/mission-vision': typeof MissionVisionRoute
  '/motto': typeof MottoRoute
  '/museum': typeof MuseumRoute
  '/ncc': typeof NccRoute
  '/nirf': typeof NirfRoute
  '/notices': typeof NoticesRoute
  '/nss': typeof NssRoute
  '/perspective-plan': typeof PerspectivePlanRoute
  '/principal': typeof PrincipalRoute
  '/prospectus': typeof ProspectusRoute
  '/routine': typeof RoutineRoute
  '/scholarships': typeof ScholarshipsRoute
  '/scouts-guides': typeof ScoutsGuidesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar-plant': typeof SolarPlantRoute
  '/ssr': typeof SsrRoute
  '/statutory-body': typeof StatutoryBodyRoute
  '/students-body': typeof StudentsBodyRoute
  '/support-staff': typeof SupportStaffRoute
  '/teachers': typeof TeachersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/academic-audit': typeof AcademicAuditRoute
  '/academic-calendar': typeof AcademicCalendarRoute
  '/achievements': typeof AchievementsRoute
  '/admission': typeof AdmissionRoute
  '/aishe': typeof AisheRoute
  '/alumni-achievements': typeof AlumniAchievementsRoute
  '/alumni-office-bearers': typeof AlumniOfficeBearersRoute
  '/alumni-registration': typeof AlumniRegistrationRoute
  '/annual-report': typeof AnnualReportRoute
  '/anthem': typeof AnthemRoute
  '/aqar': typeof AqarRoute
  '/best-practices': typeof BestPracticesRoute
  '/career-guidance': typeof CareerGuidanceRoute
  '/cells-clubs': typeof CellsClubsRoute
  '/code-of-conduct': typeof CodeOfConductRoute
  '/college-magazine': typeof CollegeMagazineRoute
  '/computer-lab': typeof ComputerLabRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/departments': typeof DepartmentsRoute
  '/emblem': typeof EmblemRoute
  '/environment-audit': typeof EnvironmentAuditRoute
  '/facilities-pwd': typeof FacilitiesPwdRoute
  '/faculties': typeof FacultiesRoute
  '/fees-waiver': typeof FeesWaiverRoute
  '/gallery': typeof GalleryRoute
  '/ict-classrooms': typeof IctClassroomsRoute
  '/idp': typeof IdpRoute
  '/iqac': typeof IqacRoute
  '/iqac-minutes': typeof IqacMinutesRoute
  '/leaders': typeof LeadersRoute
  '/legacy': typeof LegacyRoute
  '/library': typeof LibraryRoute
  '/mentor-mentee': typeof MentorMenteeRoute
  '/mission-vision': typeof MissionVisionRoute
  '/motto': typeof MottoRoute
  '/museum': typeof MuseumRoute
  '/ncc': typeof NccRoute
  '/nirf': typeof NirfRoute
  '/notices': typeof NoticesRoute
  '/nss': typeof NssRoute
  '/perspective-plan': typeof PerspectivePlanRoute
  '/principal': typeof PrincipalRoute
  '/prospectus': typeof ProspectusRoute
  '/routine': typeof RoutineRoute
  '/scholarships': typeof ScholarshipsRoute
  '/scouts-guides': typeof ScoutsGuidesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/solar-plant': typeof SolarPlantRoute
  '/ssr': typeof SsrRoute
  '/statutory-body': typeof StatutoryBodyRoute
  '/students-body': typeof StudentsBodyRoute
  '/support-staff': typeof SupportStaffRoute
  '/teachers': typeof TeachersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/academic-audit'
    | '/academic-calendar'
    | '/achievements'
    | '/admission'
    | '/aishe'
    | '/alumni-achievements'
    | '/alumni-office-bearers'
    | '/alumni-registration'
    | '/annual-report'
    | '/anthem'
    | '/aqar'
    | '/best-practices'
    | '/career-guidance'
    | '/cells-clubs'
    | '/code-of-conduct'
    | '/college-magazine'
    | '/computer-lab'
    | '/contact'
    | '/courses'
    | '/departments'
    | '/emblem'
    | '/environment-audit'
    | '/facilities-pwd'
    | '/faculties'
    | '/fees-waiver'
    | '/gallery'
    | '/ict-classrooms'
    | '/idp'
    | '/iqac'
    | '/iqac-minutes'
    | '/leaders'
    | '/legacy'
    | '/library'
    | '/mentor-mentee'
    | '/mission-vision'
    | '/motto'
    | '/museum'
    | '/ncc'
    | '/nirf'
    | '/notices'
    | '/nss'
    | '/perspective-plan'
    | '/principal'
    | '/prospectus'
    | '/routine'
    | '/scholarships'
    | '/scouts-guides'
    | '/sitemap.xml'
    | '/solar-plant'
    | '/ssr'
    | '/statutory-body'
    | '/students-body'
    | '/support-staff'
    | '/teachers'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/academic-audit'
    | '/academic-calendar'
    | '/achievements'
    | '/admission'
    | '/aishe'
    | '/alumni-achievements'
    | '/alumni-office-bearers'
    | '/alumni-registration'
    | '/annual-report'
    | '/anthem'
    | '/aqar'
    | '/best-practices'
    | '/career-guidance'
    | '/cells-clubs'
    | '/code-of-conduct'
    | '/college-magazine'
    | '/computer-lab'
    | '/contact'
    | '/courses'
    | '/departments'
    | '/emblem'
    | '/environment-audit'
    | '/facilities-pwd'
    | '/faculties'
    | '/fees-waiver'
    | '/gallery'
    | '/ict-classrooms'
    | '/idp'
    | '/iqac'
    | '/iqac-minutes'
    | '/leaders'
    | '/legacy'
    | '/library'
    | '/mentor-mentee'
    | '/mission-vision'
    | '/motto'
    | '/museum'
    | '/ncc'
    | '/nirf'
    | '/notices'
    | '/nss'
    | '/perspective-plan'
    | '/principal'
    | '/prospectus'
    | '/routine'
    | '/scholarships'
    | '/scouts-guides'
    | '/sitemap.xml'
    | '/solar-plant'
    | '/ssr'
    | '/statutory-body'
    | '/students-body'
    | '/support-staff'
    | '/teachers'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/academic-audit'
    | '/academic-calendar'
    | '/achievements'
    | '/admission'
    | '/aishe'
    | '/alumni-achievements'
    | '/alumni-office-bearers'
    | '/alumni-registration'
    | '/annual-report'
    | '/anthem'
    | '/aqar'
    | '/best-practices'
    | '/career-guidance'
    | '/cells-clubs'
    | '/code-of-conduct'
    | '/college-magazine'
    | '/computer-lab'
    | '/contact'
    | '/courses'
    | '/departments'
    | '/emblem'
    | '/environment-audit'
    | '/facilities-pwd'
    | '/faculties'
    | '/fees-waiver'
    | '/gallery'
    | '/ict-classrooms'
    | '/idp'
    | '/iqac'
    | '/iqac-minutes'
    | '/leaders'
    | '/legacy'
    | '/library'
    | '/mentor-mentee'
    | '/mission-vision'
    | '/motto'
    | '/museum'
    | '/ncc'
    | '/nirf'
    | '/notices'
    | '/nss'
    | '/perspective-plan'
    | '/principal'
    | '/prospectus'
    | '/routine'
    | '/scholarships'
    | '/scouts-guides'
    | '/sitemap.xml'
    | '/solar-plant'
    | '/ssr'
    | '/statutory-body'
    | '/students-body'
    | '/support-staff'
    | '/teachers'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AcademicAuditRoute: typeof AcademicAuditRoute
  AcademicCalendarRoute: typeof AcademicCalendarRoute
  AchievementsRoute: typeof AchievementsRoute
  AdmissionRoute: typeof AdmissionRoute
  AisheRoute: typeof AisheRoute
  AlumniAchievementsRoute: typeof AlumniAchievementsRoute
  AlumniOfficeBearersRoute: typeof AlumniOfficeBearersRoute
  AlumniRegistrationRoute: typeof AlumniRegistrationRoute
  AnnualReportRoute: typeof AnnualReportRoute
  AnthemRoute: typeof AnthemRoute
  AqarRoute: typeof AqarRoute
  BestPracticesRoute: typeof BestPracticesRoute
  CareerGuidanceRoute: typeof CareerGuidanceRoute
  CellsClubsRoute: typeof CellsClubsRoute
  CodeOfConductRoute: typeof CodeOfConductRoute
  CollegeMagazineRoute: typeof CollegeMagazineRoute
  ComputerLabRoute: typeof ComputerLabRoute
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  DepartmentsRoute: typeof DepartmentsRoute
  EmblemRoute: typeof EmblemRoute
  EnvironmentAuditRoute: typeof EnvironmentAuditRoute
  FacilitiesPwdRoute: typeof FacilitiesPwdRoute
  FacultiesRoute: typeof FacultiesRoute
  FeesWaiverRoute: typeof FeesWaiverRoute
  GalleryRoute: typeof GalleryRoute
  IctClassroomsRoute: typeof IctClassroomsRoute
  IdpRoute: typeof IdpRoute
  IqacRoute: typeof IqacRoute
  IqacMinutesRoute: typeof IqacMinutesRoute
  LeadersRoute: typeof LeadersRoute
  LegacyRoute: typeof LegacyRoute
  LibraryRoute: typeof LibraryRoute
  MentorMenteeRoute: typeof MentorMenteeRoute
  MissionVisionRoute: typeof MissionVisionRoute
  MottoRoute: typeof MottoRoute
  MuseumRoute: typeof MuseumRoute
  NccRoute: typeof NccRoute
  NirfRoute: typeof NirfRoute
  NoticesRoute: typeof NoticesRoute
  NssRoute: typeof NssRoute
  PerspectivePlanRoute: typeof PerspectivePlanRoute
  PrincipalRoute: typeof PrincipalRoute
  ProspectusRoute: typeof ProspectusRoute
  RoutineRoute: typeof RoutineRoute
  ScholarshipsRoute: typeof ScholarshipsRoute
  ScoutsGuidesRoute: typeof ScoutsGuidesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SolarPlantRoute: typeof SolarPlantRoute
  SsrRoute: typeof SsrRoute
  StatutoryBodyRoute: typeof StatutoryBodyRoute
  StudentsBodyRoute: typeof StudentsBodyRoute
  SupportStaffRoute: typeof SupportStaffRoute
  TeachersRoute: typeof TeachersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teachers': {
      id: '/teachers'
      path: '/teachers'
      fullPath: '/teachers'
      preLoaderRoute: typeof TeachersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/support-staff': {
      id: '/support-staff'
      path: '/support-staff'
      fullPath: '/support-staff'
      preLoaderRoute: typeof SupportStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/students-body': {
      id: '/students-body'
      path: '/students-body'
      fullPath: '/students-body'
      preLoaderRoute: typeof StudentsBodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/statutory-body': {
      id: '/statutory-body'
      path: '/statutory-body'
      fullPath: '/statutory-body'
      preLoaderRoute: typeof StatutoryBodyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ssr': {
      id: '/ssr'
      path: '/ssr'
      fullPath: '/ssr'
      preLoaderRoute: typeof SsrRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solar-plant': {
      id: '/solar-plant'
      path: '/solar-plant'
      fullPath: '/solar-plant'
      preLoaderRoute: typeof SolarPlantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scouts-guides': {
      id: '/scouts-guides'
      path: '/scouts-guides'
      fullPath: '/scouts-guides'
      preLoaderRoute: typeof ScoutsGuidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scholarships': {
      id: '/scholarships'
      path: '/scholarships'
      fullPath: '/scholarships'
      preLoaderRoute: typeof ScholarshipsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/routine': {
      id: '/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof RoutineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prospectus': {
      id: '/prospectus'
      path: '/prospectus'
      fullPath: '/prospectus'
      preLoaderRoute: typeof ProspectusRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/principal': {
      id: '/principal'
      path: '/principal'
      fullPath: '/principal'
      preLoaderRoute: typeof PrincipalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/perspective-plan': {
      id: '/perspective-plan'
      path: '/perspective-plan'
      fullPath: '/perspective-plan'
      preLoaderRoute: typeof PerspectivePlanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nss': {
      id: '/nss'
      path: '/nss'
      fullPath: '/nss'
      preLoaderRoute: typeof NssRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notices': {
      id: '/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof NoticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nirf': {
      id: '/nirf'
      path: '/nirf'
      fullPath: '/nirf'
      preLoaderRoute: typeof NirfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ncc': {
      id: '/ncc'
      path: '/ncc'
      fullPath: '/ncc'
      preLoaderRoute: typeof NccRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/museum': {
      id: '/museum'
      path: '/museum'
      fullPath: '/museum'
      preLoaderRoute: typeof MuseumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/motto': {
      id: '/motto'
      path: '/motto'
      fullPath: '/motto'
      preLoaderRoute: typeof MottoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mission-vision': {
      id: '/mission-vision'
      path: '/mission-vision'
      fullPath: '/mission-vision'
      preLoaderRoute: typeof MissionVisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor-mentee': {
      id: '/mentor-mentee'
      path: '/mentor-mentee'
      fullPath: '/mentor-mentee'
      preLoaderRoute: typeof MentorMenteeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/library': {
      id: '/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof LibraryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legacy': {
      id: '/legacy'
      path: '/legacy'
      fullPath: '/legacy'
      preLoaderRoute: typeof LegacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaders': {
      id: '/leaders'
      path: '/leaders'
      fullPath: '/leaders'
      preLoaderRoute: typeof LeadersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iqac-minutes': {
      id: '/iqac-minutes'
      path: '/iqac-minutes'
      fullPath: '/iqac-minutes'
      preLoaderRoute: typeof IqacMinutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/iqac': {
      id: '/iqac'
      path: '/iqac'
      fullPath: '/iqac'
      preLoaderRoute: typeof IqacRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/idp': {
      id: '/idp'
      path: '/idp'
      fullPath: '/idp'
      preLoaderRoute: typeof IdpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ict-classrooms': {
      id: '/ict-classrooms'
      path: '/ict-classrooms'
      fullPath: '/ict-classrooms'
      preLoaderRoute: typeof IctClassroomsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gallery': {
      id: '/gallery'
      path: '/gallery'
      fullPath: '/gallery'
      preLoaderRoute: typeof GalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fees-waiver': {
      id: '/fees-waiver'
      path: '/fees-waiver'
      fullPath: '/fees-waiver'
      preLoaderRoute: typeof FeesWaiverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faculties': {
      id: '/faculties'
      path: '/faculties'
      fullPath: '/faculties'
      preLoaderRoute: typeof FacultiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/facilities-pwd': {
      id: '/facilities-pwd'
      path: '/facilities-pwd'
      fullPath: '/facilities-pwd'
      preLoaderRoute: typeof FacilitiesPwdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/environment-audit': {
      id: '/environment-audit'
      path: '/environment-audit'
      fullPath: '/environment-audit'
      preLoaderRoute: typeof EnvironmentAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/emblem': {
      id: '/emblem'
      path: '/emblem'
      fullPath: '/emblem'
      preLoaderRoute: typeof EmblemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/departments': {
      id: '/departments'
      path: '/departments'
      fullPath: '/departments'
      preLoaderRoute: typeof DepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/computer-lab': {
      id: '/computer-lab'
      path: '/computer-lab'
      fullPath: '/computer-lab'
      preLoaderRoute: typeof ComputerLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college-magazine': {
      id: '/college-magazine'
      path: '/college-magazine'
      fullPath: '/college-magazine'
      preLoaderRoute: typeof CollegeMagazineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/code-of-conduct': {
      id: '/code-of-conduct'
      path: '/code-of-conduct'
      fullPath: '/code-of-conduct'
      preLoaderRoute: typeof CodeOfConductRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cells-clubs': {
      id: '/cells-clubs'
      path: '/cells-clubs'
      fullPath: '/cells-clubs'
      preLoaderRoute: typeof CellsClubsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/career-guidance': {
      id: '/career-guidance'
      path: '/career-guidance'
      fullPath: '/career-guidance'
      preLoaderRoute: typeof CareerGuidanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/best-practices': {
      id: '/best-practices'
      path: '/best-practices'
      fullPath: '/best-practices'
      preLoaderRoute: typeof BestPracticesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aqar': {
      id: '/aqar'
      path: '/aqar'
      fullPath: '/aqar'
      preLoaderRoute: typeof AqarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anthem': {
      id: '/anthem'
      path: '/anthem'
      fullPath: '/anthem'
      preLoaderRoute: typeof AnthemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annual-report': {
      id: '/annual-report'
      path: '/annual-report'
      fullPath: '/annual-report'
      preLoaderRoute: typeof AnnualReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni-registration': {
      id: '/alumni-registration'
      path: '/alumni-registration'
      fullPath: '/alumni-registration'
      preLoaderRoute: typeof AlumniRegistrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni-office-bearers': {
      id: '/alumni-office-bearers'
      path: '/alumni-office-bearers'
      fullPath: '/alumni-office-bearers'
      preLoaderRoute: typeof AlumniOfficeBearersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/alumni-achievements': {
      id: '/alumni-achievements'
      path: '/alumni-achievements'
      fullPath: '/alumni-achievements'
      preLoaderRoute: typeof AlumniAchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aishe': {
      id: '/aishe'
      path: '/aishe'
      fullPath: '/aishe'
      preLoaderRoute: typeof AisheRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admission': {
      id: '/admission'
      path: '/admission'
      fullPath: '/admission'
      preLoaderRoute: typeof AdmissionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/achievements': {
      id: '/achievements'
      path: '/achievements'
      fullPath: '/achievements'
      preLoaderRoute: typeof AchievementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-calendar': {
      id: '/academic-calendar'
      path: '/academic-calendar'
      fullPath: '/academic-calendar'
      preLoaderRoute: typeof AcademicCalendarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/academic-audit': {
      id: '/academic-audit'
      path: '/academic-audit'
      fullPath: '/academic-audit'
      preLoaderRoute: typeof AcademicAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AcademicAuditRoute: AcademicAuditRoute,
  AcademicCalendarRoute: AcademicCalendarRoute,
  AchievementsRoute: AchievementsRoute,
  AdmissionRoute: AdmissionRoute,
  AisheRoute: AisheRoute,
  AlumniAchievementsRoute: AlumniAchievementsRoute,
  AlumniOfficeBearersRoute: AlumniOfficeBearersRoute,
  AlumniRegistrationRoute: AlumniRegistrationRoute,
  AnnualReportRoute: AnnualReportRoute,
  AnthemRoute: AnthemRoute,
  AqarRoute: AqarRoute,
  BestPracticesRoute: BestPracticesRoute,
  CareerGuidanceRoute: CareerGuidanceRoute,
  CellsClubsRoute: CellsClubsRoute,
  CodeOfConductRoute: CodeOfConductRoute,
  CollegeMagazineRoute: CollegeMagazineRoute,
  ComputerLabRoute: ComputerLabRoute,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  DepartmentsRoute: DepartmentsRoute,
  EmblemRoute: EmblemRoute,
  EnvironmentAuditRoute: EnvironmentAuditRoute,
  FacilitiesPwdRoute: FacilitiesPwdRoute,
  FacultiesRoute: FacultiesRoute,
  FeesWaiverRoute: FeesWaiverRoute,
  GalleryRoute: GalleryRoute,
  IctClassroomsRoute: IctClassroomsRoute,
  IdpRoute: IdpRoute,
  IqacRoute: IqacRoute,
  IqacMinutesRoute: IqacMinutesRoute,
  LeadersRoute: LeadersRoute,
  LegacyRoute: LegacyRoute,
  LibraryRoute: LibraryRoute,
  MentorMenteeRoute: MentorMenteeRoute,
  MissionVisionRoute: MissionVisionRoute,
  MottoRoute: MottoRoute,
  MuseumRoute: MuseumRoute,
  NccRoute: NccRoute,
  NirfRoute: NirfRoute,
  NoticesRoute: NoticesRoute,
  NssRoute: NssRoute,
  PerspectivePlanRoute: PerspectivePlanRoute,
  PrincipalRoute: PrincipalRoute,
  ProspectusRoute: ProspectusRoute,
  RoutineRoute: RoutineRoute,
  ScholarshipsRoute: ScholarshipsRoute,
  ScoutsGuidesRoute: ScoutsGuidesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SolarPlantRoute: SolarPlantRoute,
  SsrRoute: SsrRoute,
  StatutoryBodyRoute: StatutoryBodyRoute,
  StudentsBodyRoute: StudentsBodyRoute,
  SupportStaffRoute: SupportStaffRoute,
  TeachersRoute: TeachersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
